language: cpp
dist: trusty
sudo: false
os: linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/opt
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:mhier/libboost-latest'
      # - sourceline: 'ppa:libreoffice/ppa'
    packages:
      - g++-8
      # - doxygen
      # - doxygen-latex
      - boost1.67
      - graphviz

before_install:
  - chmod +x ${TRAVIS_BUILD_DIR}/script/install_travis_dependencies.sh
  - ${TRAVIS_BUILD_DIR}/script/install_travis_dependencies.sh
  - export PATH=${HOME}/opt/cmake/bin:${HOME}/opt/doxygen/bin:$PATH

script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 ${TRAVIS_BUILD_DIR}
  - make tests -j4
  - ./tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master