language: cpp
dist: trusty
sudo: false
os: linux

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
      - llvm-toolchain-trusty-6-0
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - g++-8
      - clang-7
      - libclang-7-dev
      - libclang-6-dev
      - boost1.67
      - graphviz

cache:
  directories:
    - $HOME/opt
  apt: true

before_install:
  - echo "==> Installing CMake 3.12..."
  - wget https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh
  - mkdir -p ${HOME}/opt/cmake
  - sh cmake-3.12.0-Linux-x86_64.sh --prefix=${HOME}/opt/cmake --skip-license
  - echo "==> Installing Doxygen 1.8.14..."
  - wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.linux.bin.tar.gz
  - tar vxf doxygen-1.8.14.linux.bin.tar.gz
  - cp -r doxygen-1.8.14 ${HOME}/opt/doxygen
  - export PATH=${HOME}/opt/cmake/bin:${HOME}/opt/doxygen/bin:$PATH

script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 ${TRAVIS_BUILD_DIR}
  - make tests -j4
  - ./tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master