language: cpp
dist: trusty
sudo: false
os: linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/opt
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
      - sourceline: 'ppa:mhier/libboost-latest'
      - sourceline: 'ppa:mikepurvis/docs'
    packages:
      - g++-8
      - doxygen
      - libclang-7-dev
      - boost1.67
      - graphviz

before_install:
  - if [ ! -d "$HOME/opt/cmake" ]; then echo "==> Installing CMake 3.12..." && wget https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh && mkdir -p ${HOME}/opt/cmake && sh cmake-3.12.0-Linux-x86_64.sh --prefix=${HOME}/opt/cmake --skip-license; fi
  - echo "==> Installing Doxygen 1.8.14..." && chmod +x ${TRAVIS_BUILD_DIR}/script/build_doxygen.sh && ${TRAVIS_BUILD_DIR}/script/build_doxygen.sh
  - export PATH=${HOME}/opt/cmake/bin:${HOME}/opt/doxygen/bin:$PATH

script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 ${TRAVIS_BUILD_DIR}
  - make tests -j4
  - ./tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master